### ISSUE TITLE
./system.exe: error while loading shared libraries: libai.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rxyil46** [critter-mj/akochan#10]
I built it with ubuntu, but after I can see system.exe, it still couldn't start. The libai.so is existing in the root.

**Comment by jackychen651** [comment]
I have the same problem. Could you please tell me how you solved this?

**Comment by SethRobinson** [comment]
Try this:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
./system.exe test 1 2
```
