### ISSUE TITLE
Akochan doesn't consider 国士無双

### ISSUE THREAD

**Issue by hyskylord** [critter-mj/akochan#12]
Hi,

  I noticed that akochan will always call 九種九牌 even the shanten number is sufficiently low, and even I disabled "do_kyuusyukyuuhai" manually in tactics it didn't try to do 国士無双. Does akochan has a code to handle this?

  A related question to this: It seems to me akochan computes shanten number and agari score in realtime. Would it be faster to just use a lookup table?

**Comment by critter-mj** [comment]
Thank you for using akochan. Akochan does not have a code to handle 国士無双.
It is currently difficult to evaluate value of choices towards 国士無双.

Though I'm not familiar with lookup table, calculating shanten number and agari score would be faster by using it.
However, akochan uses search algorithm that yields shanten number during searching. So, using shanten number lookup table may not enhance speed.

**Comment by hyskylord** [comment]
I see. Thank you for your answer!
