### ISSUE TITLE
Incorrect furiten condition

### ISSUE THREAD

**Issue by Equim-chan** [critter-mj/akochan#8]
In https://tenhou.net/0/?log=2020091110gm-00a9-0000-3065896d&tw=2 南三1本 last turn, akochan fails to produce a tsumo hora choice.

**Comment by critter-mj** [comment]
Thank you,I fixed the bug.
Now akochan chooses hora in the situation.

2020年9月11日(金) 12:36 Equim <notifications@github.com>:
